# Generated by Django 3.2.6 on 2021-11-16 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCompulsory',
            fields=[
                ('compulsory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_id', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'DB_project"."AllCompulsory',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('likes_num', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'DB_project"."Article',
            },
        ),
        migrations.CreateModel(
            name='DepID',
            fields=[
                ('dep_id', models.TextField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'DB_project"."DepID',
            },
        ),
        migrations.CreateModel(
            name='ShareData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.TextField()),
                ('gpa_first_semester', models.TextField()),
                ('gpa_second_semester', models.TextField()),
                ('option', models.TextField()),
                ('prioity', models.TextField()),
                ('dep', models.ForeignKey(db_column='dep_id', on_delete=django.db.models.deletion.CASCADE, related_name='sharedata_dep_id', to='DB_project.depid')),
                ('user_mail', models.ForeignKey(db_column='user_mail', on_delete=django.db.models.deletion.CASCADE, related_name='sharedata_user_mail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DB_project"."ShareData',
            },
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.TextField()),
                ('vcode', models.TextField()),
            ],
            options={
                'db_table': 'DB_project"."VerifyCode',
            },
        ),
        migrations.CreateModel(
            name='DoubleMajorRequirement',
            fields=[
                ('dep', models.OneToOneField(db_column='dep_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doublemajor_dep_id', serialize=False, to='DB_project.depid')),
                ('accept_number', models.CharField(max_length=10, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('admission_requirement', models.TextField(blank=True, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DB_project"."DoubleMajorRequirement',
            },
        ),
        migrations.CreateModel(
            name='MinorRequirement',
            fields=[
                ('dep', models.OneToOneField(db_column='dep_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='minor_dep_id', serialize=False, to='DB_project.depid')),
                ('accept_number', models.CharField(max_length=10, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('admission_requirement', models.TextField(blank=True, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('compulsory', models.TextField(blank=True, null=True)),
                ('elective', models.TextField(blank=True, null=True)),
                ('min_received_credit', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DB_project"."MinorRequirement',
            },
        ),
        migrations.CreateModel(
            name='TransferRequirement',
            fields=[
                ('dep', models.OneToOneField(db_column='dep_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='transfer_dep_id', serialize=False, to='DB_project.depid')),
                ('accept_number', models.PositiveSmallIntegerField()),
                ('qualification', models.TextField(blank=True, null=True)),
                ('admission_requirement', models.TextField(blank=True, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('accept_second_priority', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DB_project"."TransferRequirement',
            },
        ),
        migrations.CreateModel(
            name='User_likes_article',
            fields=[
                ('likes_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='DB_project.article')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_likes_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DB_project"."User_likes_article',
            },
        ),
        migrations.CreateModel(
            name='TakenCompulsory',
            fields=[
                ('taken_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.TextField()),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='taken_course_id', to='DB_project.allcompulsory', to_field='course_id')),
                ('data', models.ForeignKey(db_column='data_id', on_delete=django.db.models.deletion.CASCADE, related_name='taken_data_id', to='DB_project.sharedata')),
            ],
            options={
                'db_table': 'DB_project"."TakenCompulsory',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_reply_id', models.IntegerField()),
                ('content', models.TextField()),
                ('date', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='reply_post_id', to='DB_project.article')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reply_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DB_project"."Reply',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='dep',
            field=models.ForeignKey(db_column='dep_id', on_delete=django.db.models.deletion.CASCADE, related_name='article_dep_id', to='DB_project.depid'),
        ),
        migrations.AddField(
            model_name='article',
            name='user_mail',
            field=models.ForeignKey(db_column='user_mail', on_delete=django.db.models.deletion.CASCADE, related_name='article_user_mail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TransferStats',
            fields=[
                ('year', models.TextField(blank=True, null=True)),
                ('transfer_in_applicants', models.IntegerField()),
                ('transfer_in_Approved_number', models.IntegerField()),
                ('transfer_in_Approval_rate', models.TextField(blank=True, null=True)),
                ('transfer_out_applicants', models.IntegerField()),
                ('transfer_out_winners', models.IntegerField()),
                ('transfer_out_successed_rate', models.TextField(blank=True, null=True)),
                ('id_for_transferStats', models.IntegerField(primary_key=True, serialize=False)),
                ('dep', models.ForeignKey(db_column='dep_id', on_delete=django.db.models.deletion.CASCADE, related_name='transferStats_dep_id', to='DB_project.depid')),
            ],
            options={
                'db_table': 'DB_project"."TransferStats',
                'unique_together': {('year', 'dep')},
            },
        ),
        migrations.CreateModel(
            name='MinorStats',
            fields=[
                ('year', models.TextField(blank=True, null=True)),
                ('number_of_applicants', models.IntegerField()),
                ('approved_number', models.IntegerField()),
                ('approval_rate', models.TextField(blank=True, null=True)),
                ('id_for_minorStats', models.IntegerField(primary_key=True, serialize=False)),
                ('dep', models.ForeignKey(db_column='dep_id', on_delete=django.db.models.deletion.CASCADE, related_name='minorStats_dep_id', to='DB_project.depid')),
            ],
            options={
                'db_table': 'DB_project"."MinorStats',
                'unique_together': {('year', 'dep')},
            },
        ),
        migrations.CreateModel(
            name='DoubleMajorStats',
            fields=[
                ('year', models.TextField(blank=True, null=True)),
                ('number_of_applicants', models.IntegerField()),
                ('approved_number', models.IntegerField()),
                ('approval_rate', models.TextField(blank=True, null=True)),
                ('id_for_doubleMajorStats', models.IntegerField(primary_key=True, serialize=False)),
                ('dep', models.ForeignKey(db_column='dep_id', on_delete=django.db.models.deletion.CASCADE, related_name='doubleMajorStats_dep_id', to='DB_project.depid')),
            ],
            options={
                'db_table': 'DB_project"."DoubleMajorStats',
                'unique_together': {('year', 'dep')},
            },
        ),
        migrations.CreateModel(
            name='Compulsory',
            fields=[
                ('default_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='compulsory_course_id', to='DB_project.allcompulsory', to_field='course_id')),
                ('dep', models.ForeignKey(db_column='dep_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compulsory_dep_id', to='DB_project.depid')),
            ],
            options={
                'db_table': 'DB_project"."Compulsory',
                'unique_together': {('course', 'dep')},
            },
        ),
    ]
