# Generated by Django 3.2.6 on 2022-01-20 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DB_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_likes_reply',
            fields=[
                ('likes_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_id', models.ForeignKey(db_column='reply_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='DB_project.reply')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_likes_reply', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DB_project"."User_likes_reply',
            },
        ),
    ]
