# Generated by Django 3.2.6 on 2022-01-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_project', '0003_reply_likes_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedata',
            name='ori_dep',
            field=models.TextField(default='None'),
        ),
    ]
