# Generated by Django 3.2.6 on 2022-01-26 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB_project', '0005_sharedatafail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakenCompulsoryFail',
            fields=[
                ('taken_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.TextField()),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='fali_taken_course_id', to='DB_project.allcompulsory', to_field='course_id')),
                ('data', models.ForeignKey(db_column='data_id', on_delete=django.db.models.deletion.CASCADE, related_name='fail_taken_data_id', to='DB_project.sharedatafail')),
            ],
            options={
                'db_table': 'DB_project"."TakenCompulsoryFail',
            },
        ),
    ]
